# Generated by Django 6.0.5 on 2026-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/no-image.png', null=True, upload_to='products/'),
        ),
    ]
