# Generated by Django 6.0.5 on 2026-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_shippingaddress_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='flat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
