# Generated by Django 6.0.5 on 2026-05-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_coupon_minimum_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimum_order',
            new_name='minimum_order_amount',
        ),
    ]
