# Generated by Django 6.0.5 on 2026-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_minimum_order_coupon_minimum_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
